/**
 * Export Command - Export workflow to different formats
 */

import chalk from 'chalk';
import fs from 'fs-extra';
import yaml from 'yaml';
import path from 'path';
import { Workflow } from '@promptflow/core';

interface ExportOptions {
  format: string;
  output?: string;
}

export async function runExport(workflowPath: string, options: ExportOptions) {
  try {
    // Resolve path
    const resolvedPath = workflowPath.startsWith('/') 
      ? workflowPath 
      : `${process.cwd()}/${workflowPath}`;

    // Load workflow file
    if (!fs.existsSync(resolvedPath)) {
      console.error(chalk.red(`Workflow file not found: ${resolvedPath}`));
      process.exit(1);
    }

    const content = await fs.readFile(resolvedPath, 'utf-8');
    let workflow: Workflow;

    // Parse YAML or JSON
    if (resolvedPath.endsWith('.json')) {
      workflow = JSON.parse(content);
    } else {
      workflow = yaml.parse(content) as Workflow;
    }

    // Export to requested format
    let output: string;
    let extension: string;

    switch (options.format) {
      case 'json':
        output = JSON.stringify(workflow, null, 2);
        extension = 'json';
        break;
      
      case 'yaml':
      case 'yml':
        output = yaml.stringify(workflow);
        extension = 'yaml';
        break;
      
      case 'mermaid':
        output = exportToMermaid(workflow);
        extension = 'mmd';
        break;
      
      case 'code':
        output = exportToCode(workflow);
        extension = 'ts';
        break;
      
      default:
        console.error(chalk.red(`Unknown format: ${options.format}`));
        console.log('Available formats: json, yaml, mermaid, code');
        process.exit(1);
    }

    // Write to file or stdout
    if (options.output) {
      const outputPath = path.resolve(options.output);
      await fs.writeFile(outputPath, output, 'utf-8');
      console.log(chalk.green(`✓ Exported to ${outputPath}`));
    } else {
      console.log(output);
    }

  } catch (error) {
    console.error(chalk.red('Export failed:'), error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

function exportToMermaid(workflow: Workflow): string {
  let mermaid = 'graph TD\n\n';
  
  // Add nodes
  for (const node of workflow.nodes) {
    const label = `${node.id}["${node.name}"]`;
    mermaid += `  ${label}\n`;
  }
  
  // Add edges
  for (const edge of workflow.edges) {
    mermaid += `  ${edge.source} --> ${edge.target}\n`;
  }
  
  // Add styling
  mermaid += '\n  classDef default fill:#f9f9f9,stroke:#333,stroke-width:2px\n';
  
  return '```mermaid\n' + mermaid + '```';
}

function exportToCode(workflow: Workflow): string {
  let code = `/**
 * Workflow: ${workflow.name}
 * Generated by PromptFlow
 */

import { WorkflowExecutor, Workflow } from '@promptflow/core';

const workflow: Workflow = {
  id: "${workflow.id}",
  name: "${workflow.name}",
  ${workflow.description ? `description: "${workflow.description}",` : ''}
  version: "${workflow.version}",
  nodes: [
`;

  for (const node of workflow.nodes) {
    code += `    {
      id: "${node.id}",
      name: "${node.name}",
      model: {
        provider: "${node.model.provider}",
        model: "${node.model.model}",
        temperature: ${node.model.temperature ?? 0.7}
      },
      systemPrompt: \`${node.systemPrompt || ''}\`,
      userPrompt: \`${node.userPrompt}\`
    },
`;
  }

  code += `  ],
  edges: [
`;

  for (const edge of workflow.edges) {
    code += `    { id: "${edge.id}", source: "${edge.source}", target: "${edge.target}" },\n`;
  }

  code += `  ]
};

async function main() {
  const executor = new WorkflowExecutor();
  const result = await executor.execute(workflow, {
    // Add your variables here
  });
  
  console.log('Workflow completed:', result.status);
  for (const [nodeId, nodeResult] of result.results) {
    console.log(\`[\${nodeId}]\`, nodeResult.output);
  }
}

main();
`;

  return code;
}
